export enum DB_TABLES {
    USER = 'user',
    CUSTOMER = 'customer',
    PRODUCT = 'product',
    PRODUCT_CATEGORY = 'product_category',
    PRODUCT_BRAND = 'product_brand',
    TECHNICIAN = 'technician',
    ENUM = 'enum',
    SALE = 'sale',
    REPAIR = 'repair',
    PAYMENT = 'payment',
    SALE_ITEM = 'sale_item',
    REPAIR_ITEM = 'repair_item',
    FILE_LIBRARY = 'file_library',
    SUPPLIER = 'supplier',
    PURCHASE = 'purchase',
    PURCHASE_ITEM = 'purchase_item',
    EXPENSE = 'expense',
    EXPENSE_CATEGORY = 'expense_category',
    SALE_HISTORY = 'sale_history',
    REPAIR_HISTORY = 'repair_history',
    LOG = 'log',
}


// global select fields
export const SELECT_FIELDS = {
    [DB_TABLES.PRODUCT]: [
        "id",
        "name",
        "slug",
        "sku",
        "categoryId",
        "brandId",
        "type",
        "price",
        "costPrice",
        "quantity",
        "alertQuantity",
        "weight",
        "description",
        "image",
        "status",
        "createdAt"
    ],
    [DB_TABLES.PRODUCT_CATEGORY]: [
        "id",
        "name",
        "slug",
        "description",
        "logo",
        "status",
        "createdAt"
    ],
    [DB_TABLES.PRODUCT_BRAND]: [
        "id",
        "name",
        "slug",
        "description",
        "logo",
        "status",
        "createdAt"
    ],
    [DB_TABLES.TECHNICIAN]: [
        "id",
        "name",
        "email",
        "phone",
        "address",
        "createdAt"
    ],
    [DB_TABLES.SUPPLIER]: [
        "id",
        "name",
        "email",
        "phone",
        "address",
        "status",
        "createdAt"
    ],
    [DB_TABLES.CUSTOMER]: [
        "id",
        "name",
        "email",
        "phone",
        "address",
        "createdAt"
    ],
    [DB_TABLES.USER]: [
        "id",
        "name",
        "email",
        "phone",
        "password",
        "address",
        "image",
        "role",
        "createdAt"
    ],
    [DB_TABLES.ENUM]: [
        "id",
        "key",
        "value",
    ],
    [DB_TABLES.SALE]: [
        "id",
        "customerId",
        "userId",
        "subTotal",
        "tax",
        "discount",
        "totalCost",
        "grandTotal",
        "paid",
        "due",
        "paymentMethod",
        "paymentStatus",
        "status",
        "saleNote",
        "paymentNote",
        "createdAt",
    ],
    [DB_TABLES.REPAIR]: [
        "id",
        "customerId",
        "technicianId",
        "userId",
        "deviceName",
        "issueDescription",
        "estimatedCost",
        "subTotal",
        "tax",
        "discount",
        "totalCost",
        "grandTotal",
        "paid",
        "due",
        "paymentMethod",
        "paymentStatus",
        "status",
        "repairNote",
        "paymentNote",
        "createdAt",
    ],
    [DB_TABLES.SALE_ITEM]: [
        "id",
        "saleId",
        "productId",
        "quantity",
        "unitPrice",
        "unitCost",
        "discount",
        "totalCost",
        "totalPrice",
        "createdAt",
    ],
    [DB_TABLES.REPAIR_ITEM]: [
        "id",
        "repairId",
        "technicianId",
        "productId",
        "quantity",
        "unitPrice",
        "unitCost",
        "discount",
        "totalCost",
        "totalPrice",
        "createdAt",
    ],
    [DB_TABLES.LOG]: [
        "id",
        "tableName",
        "recordId",
        "operation",
        "oldData",
        "newData",
        "userId",
        "createdAt",
    ],
    [DB_TABLES.EXPENSE_CATEGORY]: [
        "id",
        "name",
        "description",
        "status",
        "createdAt",
    ],
    [DB_TABLES.EXPENSE]: [
        "id",
        "referenceNo",
        "userId",
        "categoryId",
        "amount",
        "note",
        "expenseDate",
        "paymentMethod",
        "status",
        "document",
        "createdAt",
    ],
    [DB_TABLES.PURCHASE]: [
        "id",
        "referenceNo",
        "description",
        "supplierId",
        "userId",
        "purchaseDate",
        "discount",
        "tax",
        "paid",
        "due",
        "subTotal",
        "grandTotal",
        "paymentMethod",
        "paymentStatus",
        "status",
        "document",
        "note",
        "createdAt",
    ],
    [DB_TABLES.PURCHASE_ITEM]: [
        "id",
        "purchaseId",
        "productId",
        "quantity",
        "unitPrice",
        "discount",
        "totalPrice",
        "status",
        "note",
        "createdAt",
    ],
    [DB_TABLES.PAYMENT]: [
        "id",
        "referenceId",
        "referenceType",
        "amount",
        "paymentMethod",
        "transactionId",
        "gatewayResponse",
        "status",
        "createdAt",
    ]
}